project:
  execute-dir: project
  type: website
  render:
    - "Psychosocial/Introduction.qmd"
    - "Psychosocial/Exercise and ETOH.qmd"
    - "Psychosocial/HADS Baseline.qmd"
    - "Psychosocial/HADS Survival Analysis.qmd"
    - "Psychosocial/LifeEvents.qmd"
    - "Psychosocial/PHQ.qmd"
    - "Psychosocial/psqi.qmd"
    - "Psychosocial/QOL.qmd"
  output-dir: "../docs"
  resources:
    - "robots.txt"
    - ".nojekyll"
    - "pdf/*"

execute:
      freeze: auto
      cache: true

format:
  html:
    theme:
      light: [default, theme.scss]
      dark: [darkly]
    code-fold: true
    code-link: true
    toc: true
    toc-depth: 5
    code-tools:
      source: true
      toggle: true
    html-math-method: katex
    embed-resources: false
    mainfont: "Mulish"
    monofont: "Noto Sans Mono"
  pdf:
    toc: true
    toc-depth: 5
    fig_caption: true
    latex-engine: xelatex
    number-sections: false
website:
  title: "PREdiCCt analyses"
  twitter-card:
    creator: "@IBDNathan"
    site: "@EdinUni_IGC"
  open-graph: true
  sidebar:
    logo: "PREdiCCtlogo.png"
    style: "floating"
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/nathansam/predicct-analysis
          - text: Report a Bug
            url:  https://github.com/nathansam/predicct-analysis/issues
    search: true
    contents:
      - "index.qmd"
      - "Baseline/Recruitment.qmd"
      - section: "Baseline Analyses"
        contents:
          - "Baseline/Introduction.qmd"
          - "Baseline/Demographics.qmd"
          - "Baseline/IBD.qmd"
          - "Baseline/Biochemistry.qmd"
          - "Baseline/Diet.qmd"
          - "Baseline/Tables.qmd"
      - section: "Time to flare"
        contents:
          - "Survival/Introduction.qmd"
          - "Survival/Soft-hard-flares.qmd"
          - "Survival/Controlled.qmd"
          - "Survival/Demographics.qmd"
          - "Survival/IBD.qmd"
          - "Survival/Biochemistry.qmd"
          - "Survival/Diet.qmd"
      - "documents.qmd"
  page-footer:
    background: "#dff1f3"
    foreground: "#000000"
    left: "Copyright 2024, The Authors"
    right:
      - icon: github
        href: https://github.com/nathansam/predicct-analysis
      - icon: twitter
        href: https://twitter.com/IBDNathan
  page-navigation: true
  repo-url: https://github.com/nathansam/predicct-analysis
  repo-actions: [issue]
  favicon: "../images/favicon.png"

google-scholar: true
date: "last-modified"
title-block-banner: false


affiliations:
  - id: HGU
    name: "MRC Human Genetics Unit"
    city: "Edinburgh"
    region: "Scotland"
    country: "United Kingdom"
    url: "https://www.ed.ac.uk/mrc-human-genetics-unit"
  - id: CGEM
    name: "Centre for Genomic and Experimental Medicine"
    city: "Edinburgh"
    country: "United Kingdom"
    url: "https://www.ed.ac.uk/centre-genomic-medicine"
  - id: IBD
    name: "Edinburgh IBD Unit"
    city: "Edinburgh"
    country: "United Kingdom"
    url: "https://services.nhslothian.scot/EdinburghIBDUnit/Pages/default.aspx"
  - id: Lothian
    name: "NHS Lothian"
    city: "Edinburgh"
    country: "United Kingdom"
    url: "https://services.nhslothian.scot"
  - id: Spain
    name: "Reina Sof√≠a University Hospital, Gastroenterology and Hepatology"
    city: "Cordoba"
    country: "Spain"
    url:
  - id: Turing
    name: "The Alan Turing Institute"
    city: "London"
    country: "United Kingdom"
    url: "https://www.turing.ac.uk"
  - id: PREDICT
    name: "Center for Molecular Prediction of Inflammatory Bowel Disease (PREDICT), Aalborg University"
    city: "Copenhagen"
    country: "Denmark"
    url: "https://www.predictibd.dk/"
