project:
  title: "Predicct"
  render:
    - "Baseline.qmd"
    - "TTE.qmd"

affiliations:
  - id: HGU
    name: "MRC Human Genetics Unit"
    city: "Edinburgh"
    region: "Scotland"
    country: "United Kingdom"
    url: "https://www.ed.ac.uk/mrc-human-genetics-unit"
  - id: CGEM
    name: "Centre for Genomic and Experimental Medicine"
    city: "Edinburgh"
    country: "United Kingdom"
    url: "https://www.ed.ac.uk/centre-genomic-medicine"
  - id: IBD
    name: "Edinburgh IBD Unit"
    city: "Edinburgh"
    country: "United Kingdom"
    url: "https://services.nhslothian.scot/EdinburghIBDUnit/Pages/default.aspx"
  - id: Turing
    name: "The Alan Turing Institute"
    city: "London"
    country: "United Kingdom"
    url: "https://www.turing.ac.uk"
